services:
    dmzx.newtopic.listener:
        class: dmzx\newtopic\event\listener
        arguments:
            - @template
            - @dbal.conn
            - @auth
            - @user
        tags:
            - { name: event.listener }            